name: Java with JShell Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'World'
      age:
        description: 'Age'
        required: true
        default: '30'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Compile Java
      run: javac src/UserInputExample.java

    # - name: Run Java program
    #   run: java UserInputExample
    #   env:
    #     INPUT_NAME: ${{ github.event.inputs.name }}
    #     INPUT_AGE: ${{ github.event.inputs.age }}

    - name: Run Java program
      run: java UserInputExample < input.txt
    
    - name: Run JShell Script
      run: jshell script.jsh
